### ISSUE TITLE
TODO: Add documentation

### ISSUE THREAD

**Issue by kaelemc** [srl-labs/wsl-containerlab#9]
Just to track the following things, so I don't forget:

- [x] Add note for 'use inbuilt SSH' for DevPod (in case regular settings aren't working).
- [x] Add instructions on using proxy/jump host on SecureCRT and MobaXTerm.
- [x] Add instructions on how to add/remove routes towards clab-mgmt (WSL) in Windows.

**Comment by kaelemc** [comment]
Still waiting for WSL release. I will do a semi-rewrite of the docs when this happens.

**Comment by kaelemc** [comment]
@FloSch62 Maybe you can add MobaXT specific instructions? I'm team SecureCRT 😆
